### ISSUE TITLE
Add actions for bolt

### ISSUE THREAD

**Issue by nmaludy** [StackStorm-Exchange/stackstorm-puppet#4]
Not sure if this should be in here, or a separate pack, but i at least wanted to write it down.

Puppet released a new open source project called Bolt that can do remote execution:
- Docs: https://puppet.com/docs/bolt/0.x/bolt.html
- Repo: https://github.com/puppetlabs/bolt

Would be great to have the ability to trigger this via StackStorm (similar to Ansible playbook).

I'm willing to work on this unless someone beats me to it.

**Comment by LindsayHill** [comment]
Addressed with github.com/StackStorm-Exchange/stackstorm-bolt
